export const FETCH_DEVICES = 'FETCH_DEVICES';
export const FETCH_DEVICES_PENDING = 'FETCH_DEVICES_PENDING';
export const FETCH_DEVICES_FULFILLED = 'FETCH_DEVICES_FULFILLED';
export const FETCH_DEVICES_REJECTED = 'FETCH_DEVICES_REJECTED';

export const DEVICE_STATUS = 'DEVICE_STATUS';
export const DEVICE_STATUS_PENDING = 'DEVICE_STATUS_PENDING';
export const DEVICE_STATUS_FULFILLED = 'DEVICE_STATUS_FULFILLED';
export const DEVICE_STATUS_REJECTED = 'FETCH_DEVICES_REJECTED';
